baseURL: "https://johnhollowell.com/cpsc/"
languageCode: "en-us"
title: "CPSC Learning Lessons"
theme: "ace-doc"
publishdir: "public/"
outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
enableEmoji: true
enableRobotsTXT: true

# allow raw HTML in .md files to be passed through to the final page
markup:
  goldmark:
    renderer:
      unsafe: true

# pulls information from git commit for modified date and info
enableGitInfo: true
params:
  ordersectionsby: "weight"
  ghrepo: "https://github.com/jhollowe/cpsc/"

# TODO replace with more privacy-minded analytics
googleAnalytics: "UA-36251750-13"

# Add things to the header navbar
# menu:
#   shortcuts:
#     - name: "<i class='fab fa-github'></i>"
#       url: "https://github.com/jhollowe/cpsc"
#       weight: "1"
